### ISSUE TITLE
Support HTTP compression

### ISSUE THREAD

**Issue by acme** [JakeChampion/c-at-e-file-server#5]
To speed up published sites, we should serve compressed (Brotli & gzip) response bodies.

**Comment by JakeChampion** [comment]
Hmm, ahead of time compression could be an option here, that way we can dial it up to 11

**Comment by JakeChampion** [comment]
Instead of ahead-of-time compression, I've gone with dynamic compression using Fastly instead 👍 
JS example: https://github.com/JakeChampion/c-at-e-file-server/commit/8831243ae720949b9ebe528bc14ad092dbb642de

Rust example: https://github.com/JakeChampion/c-at-e-file-server/commit/b7c002ae97c6ba55c6aae4dbaff7d403515dedd3
